package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init [zsh|bash]",
	Short: "Output shell integration code to eval in your shell config",
	Long: `Outputs shell integration code for the given shell.

Add to the end of your ~/.zshrc or ~/.bashrc (after PATH is set):

  export PATH="$HOME/.local/bin:$PATH"
  eval "$(git-workspace shell-init zsh)"   # or: bash

This sets up the 'gws' shell function with tab completion. Because the
function is generated by the binary at shell startup, it always reflects
the current version of git-workspace — no manual updates needed.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash"},
	RunE:      runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

const zshInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
if ! type compdef &>/dev/null; then
  autoload -U compinit && compinit
fi
function gws() {
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|-*|__*) {BIN} "$@" ;;
    *) cd "$({BIN} -g "$1" -q)" ;;
  esac
}
source <({BIN} completion zsh)
compdef _git-workspace gws
`

const bashInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
function gws() {
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|-*|__*) {BIN} "$@"; return ;;
    *)
      local dest
      dest="$({BIN} -g "$1" -q 2>/dev/null)"
      [[ -n "$dest" ]] && cd "$dest"
      ;;
  esac
}
source <({BIN} completion bash)
complete -F _git-workspace gws
`

func runShellInit(_ *cobra.Command, args []string) error {
	var tmpl string
	switch args[0] {
	case "zsh":
		tmpl = zshInitTemplate
	case "bash":
		tmpl = bashInitTemplate
	default:
		return fmt.Errorf("unsupported shell %q (supported: zsh, bash)", args[0])
	}
	fmt.Print(strings.ReplaceAll(tmpl, "{BIN}", "git-workspace"))
	return nil
}
