package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init [zsh|bash|powershell]",
	Short: "Output shell integration code to eval in your shell config",
	Long: `Outputs shell integration code for the given shell.

Add to the end of your ~/.zshrc or ~/.bashrc (after PATH is set):

  export PATH="$HOME/.local/bin:$PATH"
  eval "$(git-workspace shell-init zsh)"   # or: bash

For PowerShell, add to your $PROFILE:

  $env:Path = "$HOME\.local\bin;$env:Path"
  Invoke-Expression (& git-workspace shell-init powershell | Out-String)

This sets up the 'gws' shell function with tab completion. Because the
function is generated by the binary at shell startup, it always reflects
the current version of git-workspace — no manual updates needed.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash", "powershell"},
	RunE:      runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

const zshInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
if ! type compdef &>/dev/null; then
  autoload -U compinit && compinit
fi
function gws() {
  local _dest
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__*) {BIN} "$@" ;;
    worktree)
      case "$2" in
        list|align|add|"") {BIN} "$@" ;;
        *)
          _dest="$({BIN} "$@" -q 2>/dev/tty </dev/tty)"
          [[ -n "$_dest" ]] && cd "$_dest"
          ;;
      esac
      ;;
    -p|--parent|parent)
      _dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        _dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          _dest="$({BIN} "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          _dest="$({BIN} "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$_dest" ]] && cd "$_dest"
        return
      else
        _dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
  esac
}
source <({BIN} completion zsh)
compdef _git-workspace gws
`

const bashInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init

# Ensure bash-completion helpers are available for tab completion.
# Cobra's generated completion script requires _get_comp_words_by_ref
# which comes from the bash-completion package.
if ! type _get_comp_words_by_ref &>/dev/null; then
  if [[ -r /usr/local/etc/profile.d/bash_completion.sh ]]; then
    source /usr/local/etc/profile.d/bash_completion.sh
  elif [[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
    source /opt/homebrew/etc/profile.d/bash_completion.sh
  elif [[ -r /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
  elif [[ -r /etc/bash_completion ]]; then
    source /etc/bash_completion
  fi
fi

function gws() {
  local dest
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__*) {BIN} "$@"; return ;;
    worktree)
      case "$2" in
        list|align|add|"") {BIN} "$@" ;;
        *)
          dest="$({BIN} "$@" -q 2>/dev/tty </dev/tty)"
          [[ -n "$dest" ]] && cd "$dest"
          ;;
      esac
      ;;
    -p|--parent|parent)
      dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$dest" ]] && cd "$dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          dest="$({BIN} "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          dest="$({BIN} "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$dest" ]] && cd "$dest"
        return
      else
        dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$dest" ]] && cd "$dest"
      ;;
  esac
}
source <({BIN} completion bash)
complete -o default -F __start_git-workspace gws
`

const powershellInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
function gws {
    if ($args.Count -eq 0) {
        & {BIN}
        return
    }

    $first = $args[0]
    $rest = @()
    if ($args.Count -gt 1) {
        $rest = $args[1..($args.Count - 1)]
    }

    switch -Regex ($first) {
        '^(list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__.*)$' {
            & {BIN} @args
            return
        }
        '^worktree$' {
            if ($rest.Count -eq 0) {
                & {BIN} @args
                return
            }
            $second = $rest[0]
            switch ($second) {
                { $_ -in 'list', 'align', 'add' } {
                    & {BIN} @args
                    return
                }
                default {
                    $dest = & {BIN} @args -q 2>&1 | Where-Object { $_ -is [string] }
                    if ($dest) { Set-Location $dest }
                    return
                }
            }
        }
        '^(-p|--parent|parent)$' {
            $second = if ($rest.Count -gt 0) { $rest[0] } else { $null }
            $dest = & {BIN} parent $second -q 2>&1 | Where-Object { $_ -is [string] }
            if ($dest) { Set-Location $dest }
            return
        }
        '^-' {
            & {BIN} @args
            return
        }
        default {
            $second = if ($rest.Count -gt 0) { $rest[0] } else { $null }

            if ($second -eq '-p' -or $second -eq '--parent') {
                $dest = & {BIN} parent $first -q 2>&1 | Where-Object { $_ -is [string] }
                if ($dest) { Set-Location $dest }
                return
            }
            elseif ($second -eq '-wt') {
                if ($rest.Count -gt 1) {
                    $branch = $rest[1]
                    $dest = & {BIN} $first --worktree $branch -q 2>&1 | Where-Object { $_ -is [string] }
                } else {
                    $dest = & {BIN} $first --worktree -q 2>&1 | Where-Object { $_ -is [string] }
                }
                if ($dest) { Set-Location $dest }
                return
            }
            else {
                $dest = & {BIN} $first -q 2>&1 | Where-Object { $_ -is [string] }
                if ($dest) { Set-Location $dest }
                return
            }
        }
    }
}
& {BIN} completion powershell | Invoke-Expression
(& {BIN} completion powershell) -replace 'git-workspace', 'gws' | Invoke-Expression
`

func runShellInit(_ *cobra.Command, args []string) error {
	var tmpl string
	switch args[0] {
	case "zsh":
		tmpl = zshInitTemplate
	case "bash":
		tmpl = bashInitTemplate
	case "powershell", "pwsh":
		tmpl = powershellInitTemplate
	default:
		return fmt.Errorf("unsupported shell %q (supported: zsh, bash, powershell)", args[0])
	}
	fmt.Print(strings.ReplaceAll(tmpl, "{BIN}", "git-workspace"))
	return nil
}
