package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init [zsh|bash]",
	Short: "Output shell integration code to eval in your shell config",
	Long: `Outputs shell integration code for the given shell.

Add to the end of your ~/.zshrc or ~/.bashrc (after PATH is set):

  export PATH="$HOME/.local/bin:$PATH"
  eval "$(git-workspace shell-init zsh)"   # or: bash

This sets up the 'gws' shell function with tab completion. Because the
function is generated by the binary at shell startup, it always reflects
the current version of git-workspace — no manual updates needed.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash"},
	RunE:      runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

const zshInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
if ! type compdef &>/dev/null; then
  autoload -U compinit && compinit
fi
function gws() {
  local _dest
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|worktree|help|__*) {BIN} "$@" ;;
    -p|--parent|parent)
      _dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        _dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          _dest="$({BIN} -g "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          _dest="$({BIN} -g "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$_dest" ]] && cd "$_dest"
        return
      else
        _dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
  esac
}
source <({BIN} completion zsh)
compdef _git-workspace gws
`

const bashInitTemplate = `# git-workspace shell integration — do not edit, managed via shell-init
function gws() {
  local dest
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|worktree|help|__*) {BIN} "$@"; return ;;
    -p|--parent|parent)
      dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$dest" ]] && cd "$dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          dest="$({BIN} -g "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          dest="$({BIN} -g "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$dest" ]] && cd "$dest"
        return
      else
        dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$dest" ]] && cd "$dest"
      ;;
  esac
}
source <({BIN} completion bash)
complete -F _git-workspace gws
`

func runShellInit(_ *cobra.Command, args []string) error {
	var tmpl string
	switch args[0] {
	case "zsh":
		tmpl = zshInitTemplate
	case "bash":
		tmpl = bashInitTemplate
	default:
		return fmt.Errorf("unsupported shell %q (supported: zsh, bash)", args[0])
	}
	fmt.Print(strings.ReplaceAll(tmpl, "{BIN}", "git-workspace"))
	return nil
}
