# Homebrew-core candidate formula.
#
# This is NOT the formula users install today — that one lives in the
# daileyo/homebrew-omgitworks tap and is generated by GoReleaser from prebuilt
# release binaries. homebrew-core does not accept prebuilt binaries, so a
# submission there needs this shape instead: built from source, from an
# immutable tag, with a checksum.
#
# Kept here so submitting to homebrew-core is a copy, not a rewrite, once the
# notability requirements are met. See packaging/homebrew/README.md.
class Omgitworks < Formula
  desc "Discover, organize, and navigate git repositories"
  homepage "https://omgitworks.dev"
  url "https://github.com/daileyo/omgitworks/archive/refs/tags/vVERSION.tar.gz"
  sha256 "REPLACE_WITH_RELEASE_TARBALL_SHA256"
  license "Apache-2.0"
  head "https://github.com/daileyo/omgitworks.git", branch: "main"

  depends_on "go" => :build

  def install
    ldflags = %W[
      -X main.version=#{version}
      -X main.commit=homebrew
      -X main.date=#{time.iso8601}
    ]
    system "go", "build", *std_go_args(ldflags:), "./cmd/omgitworks"

    generate_completions_from_executable(bin/"omgitworks", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omgitworks --version")

    # shell-init must emit a loadable integration script for each shell
    %w[zsh bash powershell].each do |shell|
      assert_match "omgw", shell_output("#{bin}/omgitworks shell-init #{shell}")
    end

    # with no workspace configured, the tool should say so rather than crash
    output = shell_output("#{bin}/omgitworks list 2>&1", 1)
    assert_match "not initialized", output
  end
end
